$font = Inter Display
$fontColor = rgb(204, 204, 204)

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = ~/.images/sri-lanka.jpeg
}

input-field {
    monitor =
    size = 200, 40
    outline_thickness = 0
    inner_color = rgba(28,30,38,0.8)
    check_color = rgba(28,30,38,0.8)
    fail_color = rgba(28,30,38,0.8)

    font_color = $fontColor
    font_family = $font ExtraBold
    placeholder_text = 
    fail_text = $PAMFAIL
    fade_on_empty = true
    rounding = 30

    dots_spacing = 0.3

    position = 0, 80
    halign = center
    valign = bottom
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%a %b %d" # update every 60 seconds
    font_size = 20
    font_family = $font SemiBold
    color = $fontColor

    position = 0, -80
    halign = center
    valign = top
}

# TIME
label {
    monitor =
    text = $TIME
    font_size = 110
    font_family = $font ExtraBold
    color = $fontColor

    position = 0, -100
    halign = center
    valign = top
}

